FROM m.daocloud.io/docker.io/library/maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /workspace
COPY pom.xml settings.xml ./
COPY ruoyi-common ./ruoyi-common
COPY ruoyi-api ./ruoyi-api
COPY ruoyi-modules ./ruoyi-modules
RUN mvn -s settings.xml clean package -DskipTests -pl ruoyi-modules/ruoyi-system -am

FROM m.daocloud.io/docker.io/library/eclipse-temurin:17-jre
MAINTAINER ruoyi
VOLUME /home/ruoyi
RUN mkdir -p /home/ruoyi
WORKDIR /home/ruoyi
COPY --from=builder /workspace/ruoyi-modules/ruoyi-system/target/ruoyi-modules-system.jar /home/ruoyi/ruoyi-modules-system.jar
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar ruoyi-modules-system.jar"]
