# ============================================================
# Dev overlay: 开发环境
# ============================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ruoyi-dev

resources:
  - namespace.yaml
  - acr-auth.yaml
  - service-lb.yaml
  - ../../base

configMapGenerator:
  - name: app-profile
    literals:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=f75b4571-5566-4bea-8eea-c336597af08e
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=f75b4571-5566-4bea-8eea-c336597af08e
      - SPRING_CLOUD_NACOS_CONFIG_TIMEOUT=30000
      - SPRING_DATA_REDIS_HOST=r-bp1nwyjw7nk1ng1il8.redis.rds.aliyuncs.com
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=Cai@123456
      - SPRING_DATASOURCE_DYNAMIC_PRIMARY=master
      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_MASTER_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_MASTER_URL=jdbc:mysql://rm-bp1j67t523vb8tiye.mysql.rds.aliyuncs.com:3306/ry-cloud-dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_MASTER_USERNAME=root
      - SPRING_DATASOURCE_DYNAMIC_DATASOURCE_MASTER_PASSWORD=Cai@123456
