# 基础镜像
FROM m.daocloud.io/docker.io/library/eclipse-temurin:17-jre
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY jar/ruoyi-modules-workflow.jar /home/ruoyi/ruoyi-modules-workflow.jar
# 启动工作流服务
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar ruoyi-modules-workflow.jar"]
