# ????????? Slf4J?????? Logback ?????
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
# ????????????????????? SQL
customLogMessageFormat=%(sql)
# ??? SQL ???????
outagedetection=true
outagedetectioninterval=2000
# ?????????????????????
excludecategories=info,debug,result,commit,rollback,resultset
# ??????
dateformat=yyyy-MM-dd HH:mm:ss